// Errors
const GET_ERRORS = 'GET_ERRORS';

// Users
const SET_USER = 'SET_USER';

// Profile
const GET_PROFILE = 'GET_PROFILE';
const PROFILE_LOADING = 'PROFILE_LOADING';
const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
const GET_PROFILES = 'GET_PROFILES';

// Post
const GET_POST = 'GET_POST';
const GET_ALL_POSTS = 'GET_ALL_POSTS';

export {
  GET_ERRORS,
  SET_USER,
  GET_PROFILE,
  PROFILE_LOADING,
  PROFILE_NOT_FOUND,
  CLEAR_CURRENT_PROFILE,
  GET_PROFILES,
  GET_POST,
  GET_ALL_POSTS
};
